Add reinstall kernel notebook
operate-first/blueprint pull request #72
Opened 2021-04-16 17:38 UTC by HumairAK

Related: https://github.com/operate-first/support/issues/148

2021-04-16 17:38 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **humairak** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @humairak` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fblueprint).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/blueprint/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["humairak"]} -->

2021-04-17 14:42 UTC, anishasthana requested changes

2021-04-17 14:42 UTC, anishasthana commented on docs/userstories/jupyterhub/reinstall_kernel.feature
> +        * I run command `ipython kernel install --user --name=${KERNELTYPE} --display-name '${DISPLAY_NAME}'
Should there be another '`' at the end of this line?

2021-04-19 10:58 UTC, tumido commented on docs/userstories/jupyterhub/reinstall_kernel.feature
> +        Then the chosen Kernel should be restarted
The kernel is not restarted, it's reinstalled.. JupyterHub/Lab will then restart the Kernel.. maybe we should be precise on that.. What about something like:

```suggestion
        Then the Kernel is restored and ready to be started by JupyterHub again
```

2021-04-19 13:41 UTC, tumido reviewed
/lgtm

2021-04-19 14:00 UTC, HumairAK commented
/approve

2021-04-19 14:00 UTC, HumairAK commented
/approve

2021-04-19 14:00 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/blueprint/pull/72#issuecomment-822490241" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fblueprint).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/blueprint/blob/main/OWNERS)~~ [HumairAK]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-04-19 14:00 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/blueprint/pull/72#issuecomment-822490265" title="Approved">HumairAK</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fblueprint).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/blueprint/blob/main/OWNERS)~~ [HumairAK]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-04-19 14:01 UTC, tumido approved these changes
/approve

2021-04-19 14:01 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/blueprint/pull/72#issuecomment-822490265" title="Approved">HumairAK</a>*, *<a href="https://github.com/operate-first/blueprint/pull/72#pullrequestreview-638905974" title="Approved">tumido</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fblueprint).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/operate-first/blueprint/blob/main/OWNERS)~~ [HumairAK,tumido]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2021-04-19 14:01 UTC, merged